import { RefreshCw } from 'lucide-react'
import {
  UniformPageLayout,
  HrPanel,
  HrPanelHeader,
  HrBtnOutline,
  HrStatCard,
} from '../uniformUi'
import ReportFiltersBar from './ReportFiltersBar'
import ReportDataTable from './ReportDataTable'
import { ReportChartGrid } from './ReportCharts'
import ReportExportMenu from './ReportExportMenu'
import ProfitLossReportSections from './ProfitLossReportSections'
import { fmtDate } from '../../utils/reportUtils'

export default function ReportPageShell({
  meta,
  schoolName,
  generatedBy,
  loading,
  error,
  filters,
  setFilter,
  resetFilters,
  filterOptions,
  report,
  onRefresh,
  onExportExcel,
  onExportCsv,
  onExportPdf,
  onPrint,
  exporting = false,
  showFilters = true,
  showSizeToggle = true,
  filterLayout = 'full',
  filterDrawerVariant = 'financial',
  printId = 'uniform-report-print',
}) {
  const periodLabel = `${fmtDate(filters.from)} → ${fmtDate(filters.to)}`
  const HeroIcon = meta?.icon
  const kpis = report?.kpis || []

  return (
    <UniformPageLayout
      eyebrow="Uniform Manager · Reports"
      title={meta?.title || 'Report'}
      subtitle={meta?.subtitle}
      HeroIcon={HeroIcon}
      headerRight={
        <div className="flex flex-wrap items-center gap-2">
          <HrBtnOutline onClick={onRefresh} disabled={loading || exporting}>
            <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
            Refresh
          </HrBtnOutline>
          <ReportExportMenu
            onExportExcel={onExportExcel}
            onExportCsv={onExportCsv}
            onExportPdf={onExportPdf}
            onPrint={onPrint}
            disabled={loading}
            exporting={exporting}
          />
        </div>
      }
      kpiTiles={kpis.slice(0, 6).map((k) => ({
        label: k.label,
        value: loading ? '…' : k.value,
        sub: k.sub,
        warn: k.warn,
      }))}
      kpiGridClassName="grid-cols-2 sm:grid-cols-3 xl:grid-cols-6"
    >
      {error && (
        <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {showFilters && (
        <HrPanel>
          <HrPanelHeader
            title="Filters"
            description={
              filterLayout === 'compact'
                ? (filterDrawerVariant === 'financial'
                  ? 'Search and date range — open More filters for class, product and profit/loss'
                  : 'Search and date range — open More filters for type, color, supplier and more')
                : 'Date range, category, supplier and more'
            }
          />
          <div className="px-5 pb-5">
            <ReportFiltersBar
              filters={filters}
              setFilter={setFilter}
              onReset={resetFilters}
              showSizeToggle={showSizeToggle}
              extraOptions={filterOptions}
              layout={filterLayout}
              drawerVariant={filterDrawerVariant}
            />
          </div>
        </HrPanel>
      )}

      <div id={printId}>
        <div className="hidden print:block text-center mb-6 border-b border-gray-300 pb-4">
          <h1 className="text-lg font-bold uppercase tracking-wide">{String(schoolName).toUpperCase()}</h1>
          <h2 className="text-sm font-semibold mt-1">Uniform Inventory Management Report</h2>
          <p className="text-xs text-gray-600 mt-2">Date Range: {periodLabel}</p>
          <p className="text-xs text-gray-600">Generated By: {generatedBy}</p>
        </div>

        {report?.dashboard && kpis.length > 4 && (
          <HrPanel>
            <HrPanelHeader title="Summary" subtitle="Key performance indicators" />
            <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-3">
              {kpis.map((k) => (
                <HrStatCard
                  key={k.key}
                  label={k.label}
                  value={loading ? '…' : k.value}
                  sub={k.sub}
                />
              ))}
            </div>
          </HrPanel>
        )}

        {report?.summary && Object.keys(report.summary).length > 0 && (
          <HrPanel>
            <HrPanelHeader title="Summary totals" />
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
              {Object.entries(report.summary).map(([key, val]) => (
                <div key={key} className="rounded-xl bg-gray-50 px-4 py-3 border border-gray-100">
                  <p className="text-[10px] uppercase tracking-wider text-gray-400 font-bold">
                    {key.replace(/([A-Z])/g, ' $1').trim()}
                  </p>
                  <p className="text-lg font-bold text-[#000435] mt-1">{typeof val === 'number' ? val.toLocaleString() : val}</p>
                </div>
              ))}
            </div>
          </HrPanel>
        )}

        {report?.sections?.length > 0 ? (
          <ProfitLossReportSections
            sections={report.sections}
            emptyMessage={report.emptyMessage}
            loading={loading}
          />
        ) : null}

        {!report?.sections?.length && report?.columns?.length > 0 && (
          <HrPanel>
            <HrPanelHeader
              title="Report data"
              subtitle={`${report.rows?.length || 0} record${report.rows?.length === 1 ? '' : 's'}`}
            />
            <ReportDataTable
              columns={report.columns}
              rows={report.rows || []}
              placeholderMessage={report.placeholder ? report.placeholderMessage : report.emptyMessage}
              variant="modern"
            />
          </HrPanel>
        )}

        {!report?.sections?.length && (report?.charts?.length > 0) && (
          <HrPanel>
            <HrPanelHeader title="Charts" subtitle="Visual analytics" />
            <ReportChartGrid charts={report.charts} />
          </HrPanel>
        )}

        <div className="rounded-2xl border border-gray-200 bg-white p-5 print:break-inside-avoid">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-sm text-gray-600">
            <div>
              <p className="text-[10px] uppercase tracking-wider text-gray-400 font-bold mb-6">Prepared By</p>
              <div className="border-t border-gray-400 pt-2 min-h-[48px]">{generatedBy}</div>
            </div>
            <div>
              <p className="text-[10px] uppercase tracking-wider text-gray-400 font-bold mb-6">Approved By</p>
              <div className="border-t border-gray-400 pt-2 min-h-[48px]" />
            </div>
            <div>
              <p className="text-[10px] uppercase tracking-wider text-gray-400 font-bold mb-6">Signature</p>
              <div className="border-t border-gray-400 pt-2 min-h-[48px]" />
            </div>
          </div>
          <p className="text-[11px] text-gray-400 mt-4 text-center">
            Generated on {new Date().toLocaleString()}
          </p>
        </div>
      </div>
    </UniformPageLayout>
  )
}
