import { jsPDF } from 'jspdf';

export function formatMoneyRWF(value) {
  const n = Number(value) || 0;
  return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'RWF', maximumFractionDigits: 0 }).format(n);
}

export function formatReceiptDate(value) {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value).slice(0, 10);
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

/** Build receipt view model from API payment row + UI context */
export function buildReceiptViewModel(payment, ctx = {}) {
  const p = payment || {};
  return {
    receiptNo: p.receipt_no || (p.id ? `RCP-${p.id}` : '—'),
    schoolName: p.school_name || ctx.schoolName || 'School',
    studentName: p.student_name || ctx.studentName || 'Student',
    studentCode: p.student_code || p.student_uid || ctx.studentCode || '—',
    className: p.class_name || ctx.className || '—',
    academicYear: p.academic_year_label || ctx.academicYear || '—',
    term: p.term || ctx.term || '—',
    amountPaid: Number(p.amount_paid || ctx.amount || 0),
    totalDue: Number(p.total_due || 0),
    balanceRemaining: Number(p.balance_remaining ?? 0),
    paymentMethod: p.payment_method || ctx.method || '—',
    bankName: p.bank_name || '',
    paidBy: p.paid_by || '',
    transactionRef: p.transaction_ref || '',
    momoPhone: p.momo_phone || '',
    notes: p.notes || ctx.note || '',
    paidAt: p.paid_at_date || ctx.paidAt || p.created_at,
    recordedAt: p.created_at || new Date().toISOString(),
    recordedBy: p.recorded_by_name || ctx.recordedBy || '',
  };
}

function renderReceiptPdf(doc, receipt) {
  const W = doc.internal.pageSize.getWidth();
  const margin = 44;
  const NAVY = [0, 4, 53];
  const GOLD = [251, 191, 36];

  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, 72, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(receipt.schoolName, margin, 32);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Official school fees receipt', margin, 52);

  doc.setDrawColor(...GOLD);
  doc.setLineWidth(4);
  doc.line(margin, 84, W - margin, 84);

  let y = 108;
  doc.setTextColor(...NAVY);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Payment Receipt', margin, y);
  y += 22;

  doc.setFontSize(10);
  const row = (label, value, bold = false) => {
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(label, margin, y);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setTextColor(15, 23, 42);
    doc.text(String(value || '—'), W - margin, y, { align: 'right' });
    y += 16;
  };

  row('Receipt No.', receipt.receiptNo, true);
  row('Date paid', formatReceiptDate(receipt.paidAt));
  row('Recorded', formatReceiptDate(receipt.recordedAt));
  if (receipt.recordedBy) row('Recorded by', receipt.recordedBy);
  y += 6;

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...NAVY);
  doc.text('Student', margin, y);
  y += 16;
  row('Name', receipt.studentName);
  row('Code / UID', receipt.studentCode);
  row('Class', receipt.className);
  row('Academic year', receipt.academicYear);
  row('Term', receipt.term);
  y += 6;

  doc.setFont('helvetica', 'bold');
  doc.text('Payment', margin, y);
  y += 16;
  row('Method', receipt.paymentMethod);
  if (receipt.bankName) row('Bank', receipt.bankName);
  if (receipt.paidBy) row('Paid by', receipt.paidBy);
  if (receipt.momoPhone) row('MoMo phone', receipt.momoPhone);
  if (receipt.transactionRef) row('Transaction / receipt #', receipt.transactionRef, true);
  y += 4;

  doc.setFillColor(255, 251, 235);
  doc.roundedRect(margin, y, W - margin * 2, 52, 8, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...NAVY);
  doc.text('Amount paid', margin + 14, y + 22);
  doc.text(formatMoneyRWF(receipt.amountPaid), W - margin - 14, y + 34, { align: 'right' });
  y += 64;

  row('Total due (term)', formatMoneyRWF(receipt.totalDue));
  row('Balance remaining', formatMoneyRWF(receipt.balanceRemaining));
  if (receipt.notes) {
    y += 4;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    const lines = doc.splitTextToSize(`Note: ${receipt.notes}`, W - margin * 2);
    doc.text(lines, margin, y);
  }

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    'This receipt was generated by Babyeyi School Finance. Keep for your records.',
    margin,
    doc.internal.pageSize.getHeight() - 36
  );
}

function createReceiptPdf(receipt) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  renderReceiptPdf(doc, receipt);
  return doc;
}

export function downloadFeePaymentReceiptPdf(receipt) {
  const doc = createReceiptPdf(receipt);
  const filename = `receipt-${String(receipt.receiptNo).replace(/[^\w-]+/g, '-')}.pdf`;
  doc.save(filename);
}

export function printFeePaymentReceiptPdf(receipt) {
  const doc = createReceiptPdf(receipt);
  doc.autoPrint();
  window.open(URL.createObjectURL(doc.output('blob'), '_blank'));
}

/** Open PDF from authenticated API path (session cookie). */
export async function openAuthenticatedPdf(apiClient, apiPath) {
  const path = String(apiPath || '').replace(/^\/api/, '');
  const res = await apiClient.get(path, { responseType: 'blob' });
  const blob = new Blob([res.data], { type: 'application/pdf' });
  window.open(URL.createObjectURL(blob), '_blank');
}

export async function downloadAuthenticatedPdf(apiClient, apiPath, filename) {
  const path = String(apiPath || '').replace(/^\/api/, '');
  const res = await apiClient.get(path, { responseType: 'blob' });
  const blob = new Blob([res.data], { type: 'application/pdf' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename || 'document.pdf';
  a.click();
  URL.revokeObjectURL(a.href);
}

export function downloadHistoryItemPdf(item, ctx, apiClient) {
  if (item?.source === 'manual' && item.raw) {
    downloadFeePaymentReceiptPdf(buildReceiptViewModel(item.raw, ctx));
    return Promise.resolve();
  }
  if (item?.source === 'online') {
    const path =
      item.status === 'paid' && item.receipt_pdf_url
        ? item.receipt_pdf_url
        : item.invoice_pdf_url || item.view_url;
    if (path && apiClient) {
      const name = `${item.reference || 'invoice'}.pdf`.replace(/[^\w.-]+/g, '_');
      return downloadAuthenticatedPdf(apiClient, path, name);
    }
  }
  return Promise.resolve();
}

export function downloadAllStudentPaymentsPdf({ student, academicYear, term, items, schoolName }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const margin = 44;
  const NAVY = [0, 4, 53];
  const GOLD = [251, 191, 36];

  doc.setFillColor(...NAVY);
  doc.rect(0, 0, W, 72, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(schoolName || 'School', margin, 32);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Student payment history', margin, 52);
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(3);
  doc.line(margin, 84, W - margin, 84);

  let y = 108;
  doc.setTextColor(...NAVY);
  doc.setFontSize(10);
  doc.text(`Student: ${student?.name || '—'}`, margin, y);
  y += 14;
  doc.text(`Code: ${student?.id || '—'}   Class: ${student?.class || '—'}`, margin, y);
  y += 14;
  doc.text(`Period: ${academicYear || '—'} · ${term || '—'}`, margin, y);
  y += 20;

  const cols = [margin, margin + 72, margin + 168, margin + 248, W - margin];
  doc.setFillColor(...GOLD);
  doc.rect(margin, y - 8, W - margin * 2, 16, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text('DATE', cols[0], y + 2);
  doc.text('SOURCE', cols[1], y + 2);
  doc.text('REF', cols[2], y + 2);
  doc.text('STATUS', cols[3], y + 2);
  doc.text('AMOUNT', cols[4], y + 2, { align: 'right' });
  y += 20;

  doc.setFont('helvetica', 'normal');
  (items || []).forEach((row, i) => {
    if (y > doc.internal.pageSize.getHeight() - 60) {
      doc.addPage();
      y = margin + 20;
    }
    if (i % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, y - 9, W - margin * 2, 14, 'F');
    }
    const d = formatReceiptDate(row.date);
    doc.text(d, cols[0], y);
    doc.text(String(row.source_label || row.source || '').slice(0, 18), cols[1], y);
    doc.text(String(row.reference || '—').slice(0, 14), cols[2], y);
    doc.text(String(row.status_label || row.status || '').slice(0, 14), cols[3], y);
    doc.text(formatMoneyRWF(row.amount).replace('RWF', '').trim(), cols[4], y, { align: 'right' });
    y += 14;
  });

  const total = (items || []).reduce((s, x) => s + Number(x.amount || 0), 0);
  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.text(`Total listed: ${formatMoneyRWF(total)}`, margin, y);

  const uid = String(student?.id || 'student').replace(/\s+/g, '');
  doc.save(`payments-${uid}-${String(academicYear || '').replace(/\s+/g, '-')}.pdf`);
}
