export const PORTAL = {
  id: 'librarian',
  sessionKey: 'librarian_logged_in',
  documentTitle: 'Babyeyi · Library',
  loadingMessage: 'Loading Library Portal…',
  brandLine: 'School library',
  roleLabel: 'Librarian',
  loginBadge: 'Library Portal | Secure',
  loginEyebrow: 'School library',
  loginTitle: 'Babyeyi',
  loginHeroLine: 'Manage the school book collection, track borrowing, and keep the library running for every learner and staff member.',
  loginHeroHighlight: 'Library team',
  loginFormTitle: 'Library portal',
  loginFormSubtitle: 'Sign in to manage books, borrowing, and returns.',
  emailLabel: 'Work email',
  emailPlaceholder: 'library@school.rw',
  profileFallback: 'Librarian',
  heroImage: '/teacher.jpg',
  heroImageAlt: 'School library',
  searchPlaceholder: 'Search books, borrowers…',
};
